const elementIds = {
  connectBtn: 'connect-btn',
  mintBtn: 'mint-btn',
  disconnectBtn: 'disconnect-btn',
  copyAddressBtn: 'copy-address-btn',
  refreshBtn: 'refresh-btn',
  heroConnectBtn: 'hero-connect-btn',
  heroMarketBtn: 'hero-market-btn',
  commandCenterBtn: 'command-center-btn',
  motionToggleBtn: 'motion-toggle-btn',
  installAppBtn: 'install-app-btn',
  commandModal: 'command-modal',
  commandCloseBtn: 'command-close-btn',
  commandSearchInput: 'command-search-input',
  commandResults: 'command-results',
  themeToggle: 'theme-toggle',
  autoRefresh: 'auto-refresh',
  nftFilter: 'nft-filter',
  marketFilter: 'market-filter',
  marketSort: 'market-sort',
  marketFilterModes: Array.from(document.querySelectorAll('[data-market-filter-mode]')),
  defaultListPrice: 'default-list-price',
  priceLabInput: 'price-lab-input',
  matchFloorBtn: 'match-floor-btn',
  undercutFloorBtn: 'undercut-floor-btn',
  applyPriceLabBtn: 'apply-price-lab-btn',
  clearActivityBtn: 'clear-activity-btn',
  notConnected: 'not-connected',
  connected: 'connected',
  walletAddress: 'wallet-address',
  walletChip: 'wallet-chip',
  walletSessionState: 'wallet-session-state',
  nextSyncLabel: 'next-sync-label',
  walletState: 'wallet-state',
  walletStateDetail: 'wallet-state-detail',
  dashboardSync: 'dashboard-sync',
  dashboardSyncDetail: 'dashboard-sync-detail',
  connectionStatusLabel: 'connection-status-label',
  connectionStatusDetail: 'connection-status-detail',
  globalTrendLabel: 'global-trend-label',
  globalTrendDetail: 'global-trend-detail',
  worldClocks: 'world-clocks',
  focusModeBtn: 'focus-mode-btn',
  exportSnapshotBtn: 'export-snapshot-btn',
  focusModeLabel: 'focus-mode-label',
  marketDepthLabel: 'market-depth-label',
  marketDepthDetail: 'market-depth-detail',
  marketRegimeLabel: 'market-regime-label',
  sessionUptimeLabel: 'session-uptime-label',
  lastActivityLabel: 'last-activity-label',
  refreshModeLabel: 'refresh-mode-label',
  marketPulse: 'market-pulse',
  marketPulseDetail: 'market-pulse-detail',
  minted: 'minted',
  mintedDetail: 'minted-detail',
  mintUsdEstimate: 'mint-usd-estimate',
  mintTempo: 'mint-tempo',
  listed: 'listed',
  ownedCount: 'owned-count',
  ownedListedCount: 'owned-listed-count',
  readyToListCount: 'ready-to-list-count',
  portfolioDetail: 'portfolio-detail',
  listingCount: 'listing-count',
  listingCountDetail: 'listing-count-detail',
  salesCount: 'sales-count',
  salesCountDetail: 'sales-count-detail',
  stxPrice: 'stx-price',
  stxPriceUpdated: 'stx-price-updated',
  networkStatus: 'network-status',
  networkHeight: 'network-height',
  status: 'status',
  nftList: 'nft-list',
  marketListings: 'market-listings',
  marketSummary: 'market-summary',
  bestAsk: 'best-ask',
  averageAsk: 'average-ask',
  yourListingsCount: 'your-listings-count',
  scanWindow: 'scan-window',
  activityFeed: 'activity-feed',
  activityFilters: Array.from(document.querySelectorAll('[data-activity-filter]')),
  estimatedNet: 'estimated-net',
  priceLabStance: 'price-lab-stance',
  supplyOutlook: 'supply-outlook',
  listingStrategy: 'listing-strategy',
  walletReadiness: 'wallet-readiness',
  recommendedListPrice: 'recommended-list-price',
  coverageNote: 'coverage-note',
  mintProgressFill: 'mint-progress-fill',
  mintProgressLabel: 'mint-progress-label',
};

export const elements = {
  marketFilterModes: [],
  activityFilters: [],
};

export function resolveElements() {
  Object.entries(elementIds).forEach(([key, id]) => {
    elements[key] = document.getElementById(id);
  });

  elements.marketFilterModes = Array.from(document.querySelectorAll('[data-market-filter-mode]'));
  elements.activityFilters = Array.from(document.querySelectorAll('[data-activity-filter]'));
}
