export const state = {
  sessionStartedAt: Date.now(),
  userAddress: null,
  walletConnectInFlight: false,
  lastWalletError: null,
  userNFTs: [],
  marketListings: [],
  autoRefreshTimer: null,
  refreshInFlight: false,
  statusTimer: null,
  lastRefreshAt: null,
  refreshTickTimer: null,
  stxQuote: null,
  marketInsights: null,
  activityFilter: 'all',
  marketFilterMode: 'all',
  commandModalOpen: false,
  commandIndex: 0,
  deferredInstallPrompt: null,
  isOffline: false,
  worldClockTimer: null,
  sessionTimer: null,
};
