export const state = {
  userAddress: null,
  userNFTs: [],
  marketListings: [],
  autoRefreshTimer: null,
  refreshInFlight: false,
  statusTimer: null,
  lastRefreshAt: null,
  refreshTickTimer: null,
  stxQuote: null,
  marketInsights: null,
  activityFilter: 'all',
  commandModalOpen: false,
  commandIndex: 0,
  deferredInstallPrompt: null,
  isOffline: false,
  worldClockTimer: null,
};
